### ISSUE TITLE
node版本

### ISSUE THREAD

**Issue by shaoyuchao** [ZeeHG/mitichat_h5#1]
我想知道该用哪个版本的node来安装这个项目依赖   14  16  18版本都会报错

**Comment by ZeeHG** [comment]
我16.8没问题在 2024年7月31日，11:35，chao ***@***.***> 写道：﻿
我想知道该用哪个版本的node来安装这个项目依赖   14  16  18版本都会报错

**Comment by shaoyuchao** [comment]
![091907](https://github.com/user-attachments/assets/1c960ef7-8388-4949-8ec5-31076354b94e)

依赖都装上了,请问运行时这个报错是什么原因呢

**Comment by ZeeHG** [comment]
我刚测试了一下，在node v18.2.0的电脑上直接git clone了这个项目，拉到本地npm i之后就跑起来了，没有任何多余步骤
![微信截图_20240801114833](https://github.com/user-attachments/assets/333ecb70-328d-49f0-96c2-ec007fd86ad0)
![微信截图_20240801114839](https://github.com/user-attachments/assets/8c5c7780-1027-4c40-9923-07d79de18ee5)

**Comment by shaoyuchao** [comment]
> 我刚测试了一下，在node v18.2.0的电脑上直接git clone了这个项目，拉到本地npm i之后就跑起来了，没有任何多余步骤 ![微信截图_20240801114833](https://private-user-images.githubusercontent.com/87009998/354070699-333ecb70-328d-49f0-96c2-ec007fd86ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTA2MTcsIm5iZiI6MTcyMjQ5MDMxNywicGF0aCI6Ii84NzAwOTk5OC8zNTQwNzA2OTktMzMzZWNiNzAtMzI4ZC00OWYwLTk2YzItZWMwMDdmZDg2YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA1MzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZGU0MmY0ZTIxNWE4MTI2MmQzMmQ2YTRiZDNlMTQ3ZDM1NTM2NmQxNGYxZTg0MDkzMzY3MTAzODUyMGM0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnxFQVnQq-v6bKTwyuCPyUbwGStK-BDLslaGK12icrg) ![微信截图_20240801114839](https://private-user-images.githubusercontent.com/87009998/354070726-8c5c7780-1027-4c40-9923-07d79de18ee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTA2MTcsIm5iZiI6MTcyMjQ5MDMxNywicGF0aCI6Ii84NzAwOTk5OC8zNTQwNzA3MjYtOGM1Yzc3ODAtMTAyNy00YzQwLTk5MjMtMDdkNzlkZTE4ZWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA1MzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NTkxNTU1YWUwOGViNTkwOWQ0Y2JjOWY5NGVlNTcwNmQxM2FlN2JiMWNhNGY1MGM5YmRlNGY3ZjE4NTkyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jZmvk4o2VZtQrAuzg0u1d8nS2-8L_SjpGf4tXUlaQoQ)

好的我再试试 感谢您

**Comment by ZeeHG** [comment]
不客气
